In [1]:
import torch
import numpy as np

# Creating tensors

In [2]:
# creating tensors from python array(list) and numpy array
a = [1, 2, 3]
b = np.array([4, 5, 6], dtype = np.int32)

te_a = torch.tensor(a)
te_b = torch.tensor(b)

print(te_a)
print(te_b)

tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)


In [3]:
# creating a tensor with all element 1 
te_c = torch.ones(size = (2, 3))
print(te_c)
print(te_c.size())

tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.Size([2, 3])


- **Shape** is like a label on the outside of the box that tells you how many boxes are inside and how big they are.

- **Size** is like counting the number of boxes you have in each size. So you can say "I have 3 boxes that are big, and 4 boxes that are small"

In [4]:
# creating a tensor with all val 0 
te_d = torch.zeros((1, 2))
print(te_d)

tensor([[0., 0.]])


In [5]:
# Creating a tensor with random value
te_e = torch.rand((3,4))
print(te_e)

tensor([[0.1244, 0.7860, 0.3895, 0.9390],
        [0.1364, 0.7657, 0.6788, 0.5905],
        [0.6626, 0.6404, 0.3048, 0.4547]])


# Transforming tensors

In [6]:
# Transposing a tensor
transposed_te_e = torch.transpose(input = te_e, dim0 = 0, dim1= 1)
print(te_e.shape)
print(transposed_te_e.shape)

torch.Size([3, 4])
torch.Size([4, 3])


In [7]:
# Reshaping a tensor
te_f = torch.rand(30) #from 0-1
reshaped_te_f = te_f.reshape((5,1,6)) # all dimensions should multiply to previous one. 5*1*6 = 30
print(reshaped_te_f)

tensor([[[0.3799, 0.0516, 0.2182, 0.3438, 0.4388, 0.2983]],

        [[0.5448, 0.2657, 0.4813, 0.8509, 0.7852, 0.3157]],

        [[0.1413, 0.4893, 0.3113, 0.6023, 0.9086, 0.9579]],

        [[0.3048, 0.3211, 0.7420, 0.6447, 0.7326, 0.3396]],

        [[0.0608, 0.0896, 0.1625, 0.6864, 0.9451, 0.6563]]])


In [8]:
# Squeezing the tensors0
""" Squeezing mean:  we we have multiple demntioned tensor and some of dimention is 1, this method will get rid of that dimension., except for the dimention is first or .last of that  
like (3,4,2,1,3,1) --> (3,4,2,3, 1)"""
sqe_reshaped_te_f = reshaped_te_f.squeeze()
print(reshaped_te_f.shape)
print(sqe_reshaped_te_f.shape)

torch.Size([5, 1, 6])
torch.Size([5, 6])


# Mathematical operations on tensors

In [9]:
# Creating 2 tensor to do operations on

x = torch.rand(5,6) - 1
y = torch.normal(mean = 0, std =2.5, size = (5, 6))

In [10]:
# Element-wise multiplication
"""
Both tensors must have the same number of dimensions or one tensor must have a dimension
of size 1 that can be broadcasted to match the other tensor's shape.
"""
t3 = torch.multiply(x, y)
print(t3)

tensor([[ 1.3524, -0.2100,  0.7393,  0.0821,  0.6049,  0.4020],
        [ 0.2451, -3.8007, -1.1096, -2.0882,  1.0515, -0.3543],
        [-0.0864,  0.4024, -0.2634, -1.2567, -1.2861,  0.5221],
        [-0.1277,  0.1112,  2.4232,  0.8659, -5.6495,  1.7745],
        [ 0.4224,  0.8789, -2.1585,  0.0886, -1.1239, -0.1789]])


In [11]:
# Some more
print(torch.mean(t3, axis=1))
print(torch.sum(t3, axis=1))
print(torch.std(t3, axis=1))

tensor([ 0.4951, -1.0094, -0.3280, -0.1004, -0.3452])
tensor([ 2.9708, -6.0563, -1.9681, -0.6025, -2.0714])
tensor([0.5446, 1.7444, 0.7873, 2.8864, 1.1134])


In [12]:
# Matrix Multiplication
t4 = torch.matmul(x, torch.transpose(y, 0, 1)) 
"""
I have transposed as y becasue x and y both have same dimention and in order to do matrix , we need to match column of first to row of second
"""
print(t4)

tensor([[ 2.9708, -0.4243, -1.8371, -2.8036, -0.4817],
        [ 4.3973, -6.0563, -3.5255, -1.7716, -1.7308],
        [ 0.3145, -5.6690, -1.9681, -2.6063,  0.1925],
        [ 6.9845, -7.0363, -2.6366, -0.6025, -2.5203],
        [ 3.9466, -3.9501,  0.2167,  0.1466, -2.0714]])


In [16]:
# dot multiplication
"""
We can only do dot multiplication in 1d arrays so we have to use either .reshape(-1) or .faltten() convert the matrix in 1d before dot product
"""
t5 = torch.dot(x.flatten(), y.flatten()) 
print(t5)

tensor(-7.7276)


# Little more

In [23]:
# Chunking
"""
Chunk divide the give tensor to the given number of chunk and in given dimension. we can not specify that second chunch shoud have particular number of
element rather it is calculated by diving the number of element along the given dimention by numbet of needed chunk some time if not exactly divisible 
last chuck may have fewer element that expected
"""
t6 = torch.rand(10)
chunks = torch.chunk(t6, 3, dim=0)
for i, chunk in enumerate(chunks):
    print(f"Chunk {i} : {chunk}")

Chunk 0 : tensor([0.7648, 0.3958, 0.0978, 0.3106])
Chunk 1 : tensor([0.2060, 0.7780, 0.7123, 0.3043])
Chunk 2 : tensor([0.0859, 0.7132])


In [25]:
# Splitting
"""
Split is simmilar to chunk just we can give numnber of elements we want to have in each chunk
"""
splits = torch.split(t6, [3, 2, 5], dim = 0) # [3, 2, 5] this should add to original dimention 10
for i, split in enumerate(splits):
    print(f"split {i} : {split}")

split 0 : tensor([0.7648, 0.3958, 0.0978])
split 1 : tensor([0.3106, 0.2060])
split 2 : tensor([0.7780, 0.7123, 0.3043, 0.0859, 0.7132])
